### ISSUE TITLE
SignatureDoesNotMatch error when using Minio and GenericS3 client

### ISSUE THREAD

**Issue by Genbox** [Genbox/SimpleS3#61]
Issue described here: https://github.com/Genbox/SimpleS3/issues/59#issuecomment-2305613103

**Comment by Genbox** [comment]
This seems to be a bug that happens when using a different port than the standard 80 and 443 ports.

**Comment by holly-hacker** [comment]
I didn't think it was relevant in my original issue but I do indeed use a custom port. This is the config I use for development:
```json
"ObjectStorage": {
  "Endpoint": "localhost:30030",
  "Bucket": "test-bucket",
  "Region": "auto",
  "AccessKey": "minio_user",
  "SecretKey": "minio_pass"
}
```
while I use the following section in a docker-compose file to run minio:
```yml
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-04-06T05-26-02Z
    command: server --console-address ":9001" /data
    ports:
      - 30030:9000
      - 30031:9001
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_pass
      - MINIO_DEFAULT_BUCKET=test-bucket
```
